# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2bc9ef88dc44ecc7425b921af64b6ec30680eaf61034d1693ba71043ab9043f3a791c20238be88daed4f0e8eafe482eb1f0d385f5e4d5c403c14b91af55a1857

test:
  secret_key_base: a8d036503ccf38cf0be4f8b2f4f65665853b4504d4f044e819023d9d6a4cec2629510e3e170136fc0b877b45b35ce02a89ac41d69ee7797a9e5b270544070755

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
